In [529]:
import pandas as pd
import numpy as np

In [530]:
### Pre-Processing of Data

In [531]:
 # importing and reading the file

In [532]:
pp = pd.read_csv(r"C:\Users\DELL'\Desktop\Masters Assignment\Game Data.csv")


In [533]:
 # renaming the columns

In [534]:
pp.columns= ['X_Dist', 'Y_Dist','X_Velo', 'Y_Velo']
pp

X_Dist      Y_Dist    X_Velo   Y_Velo
0    -741.963938  431.900000  0.000000  0.00000
1    -741.963938  431.900000 -0.100000  0.04000
2    -742.003938  432.000000 -0.200000  0.00000
3    -742.003938  432.200000 -0.300000  0.04000
4    -742.043938  432.500000 -0.400000  0.00000
...          ...         ...       ...      ...
8108    8.145929   90.077252  5.687504  0.02097
8109    8.124959   84.389748  5.787504 -0.01903
8110    8.143989   78.602244  5.887504  0.02097
8111    8.123018   72.714739  5.987504 -0.01903
8112    8.142048   66.727235  6.087504  0.02097

[8113 rows x 4 columns]

In [535]:
pp.head()

X_Dist  Y_Dist  X_Velo  Y_Velo
0 -741.963938   431.9     0.0    0.00
1 -741.963938   431.9    -0.1    0.04
2 -742.003938   432.0    -0.2    0.00
3 -742.003938   432.2    -0.3    0.04
4 -742.043938   432.5    -0.4    0.00

In [536]:
pp.describe()

X_Dist       Y_Dist       X_Velo       Y_Velo
count  8113.000000  8113.000000  8113.000000  8113.000000
mean     33.725805   445.481331     1.416993     0.085099
std     279.679136   157.469487     2.971521     1.727409
min    -742.636958    65.443567    -5.211456    -5.885082
25%    -140.419021   368.144666    -0.774860    -0.661898
50%      -3.102526   445.200000     0.963586     0.000000
75%     171.395944   552.209010     3.501473     0.255461
max     804.795796   815.244208     8.000000     5.711558

In [537]:
 #Checking for null values/missing data

In [538]:
pp.isnull().sum()

X_Dist    0
Y_Dist    0
X_Velo    0
Y_Velo    0
dtype: int64

In [539]:
 # normalizing for a range of (0.0 to 1.0) using min-max scaler =(x-min(x))/(max(x)-min(x))

In [540]:
pf = ((pp-pp.min()) / (pp.max() -pp.min()))
pf

X_Dist    Y_Dist    X_Velo    Y_Velo
0     0.000435  0.488738  0.394465  0.507482
1     0.000435  0.488738  0.386896  0.510931
2     0.000409  0.488872  0.379327  0.507482
3     0.000409  0.489139  0.371757  0.510931
4     0.000383  0.489539  0.364188  0.507482
...        ...       ...       ...       ...
8108  0.485180  0.032854  0.824963  0.509290
8109  0.485166  0.025268  0.832532  0.505841
8110  0.485178  0.017550  0.840101  0.509290
8111  0.485165  0.009697  0.847670  0.505841
8112  0.485177  0.001712  0.855240  0.509290

[8113 rows x 4 columns]

In [541]:
 # Checking if data has been scaled

In [542]:
(pf.min(), pf.max())

(X_Dist    0.0
 Y_Dist    0.0
 X_Velo    0.0
 Y_Velo    0.0
 dtype: float64,
 X_Dist    1.0
 Y_Dist    1.0
 X_Velo    1.0
 Y_Velo    1.0
 dtype: float64)

In [543]:
pf.describe()


X_Dist       Y_Dist       X_Velo       Y_Velo
count  8113.000000  8113.000000  8113.000000  8113.000000
mean      0.501710     0.506852     0.501720     0.514820
std       0.180738     0.210015     0.224920     0.148958
min       0.000000     0.000000     0.000000     0.000000
25%       0.389172     0.403709     0.335814     0.450405
50%       0.477911     0.506477     0.467401     0.507482
75%       0.590677     0.649193     0.659498     0.529511
max       1.000000     1.000000     1.000000     1.000000

In [544]:
pf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8113 entries, 0 to 8112
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X_Dist  8113 non-null   float64
 1   Y_Dist  8113 non-null   float64
 2   X_Velo  8113 non-null   float64
 3   Y_Velo  8113 non-null   float64
dtypes: float64(4)
memory usage: 253.7 KB


In [545]:
# shuffling the data to avoid biasness using sample function

In [546]:
pf = pf.sample(frac=1)

In [547]:
# identifying the inputs and outputs data using the locate function 

In [548]:
inPut = pf.iloc[:,0:2]
inPut

X_Dist    Y_Dist
1445  0.591427  0.489539
3894  0.226232  0.516746
1401  0.553146  0.246442
4340  0.455336  0.448108
6447  0.999328  0.464465
...        ...       ...
7558  0.454082  0.661527
7992  0.463106  0.395723
1758  0.526871  0.573105
5084  0.471707  0.330303
5777  0.488720  0.161268

[8113 rows x 2 columns]

In [549]:
output = pf.iloc[:,2:4]
output

X_Velo    Y_Velo
1445  0.364188  0.507482
3894  0.235512  0.510931
1401  0.802838  0.683835
4340  0.353422  0.427165
6447  0.598833  0.510931
...        ...       ...
7558  0.392773  0.463875
7992  0.587081  0.505684
1758  0.728103  0.614425
5084  0.992812  0.509923
5777  0.713859  0.664366

[8113 rows x 2 columns]

In [550]:
# Splitting the data into a Train and test sets using train_test_split function with a 0.80 ratio

In [551]:
from sklearn.model_selection import train_test_split

In [552]:
Big_Train_x, test_x, Big_Train_y,  test_y = train_test_split(inPut,output,train_size =0.8)

In [553]:
Big_Train_x.shape

(6490, 2)

In [554]:
Big_Train_y.shape

(6490, 2)

In [555]:
test_x.shape

(1623, 2)

In [556]:
test_y.shape 

(1623, 2)

In [557]:
# Splitting the Big Train set, further into a  validation and a new train set with a 0.10 ratio

In [558]:
train_x, vali_x, train_y, vali_y = train_test_split(Big_Train_x,Big_Train_y,test_size =0.10)

In [559]:
train_x.shape

(5841, 2)

In [560]:
train_y.shape

(5841, 2)

In [561]:
vali_x.shape

(649, 2)

In [562]:
vali_y.shape

(649, 2)

In [563]:
# Hence: 
# Training Datas = train_x and train_y 
# Validation Datas =vali_x and vali_y 
# Test datas = test_x and test_y
# Thereafter, transposing all these datas

In [564]:
train_x = train_x.T
vali_x = vali_x.T
train_y =train_y.T
vali_y = vali_y.T
test_x = test_x.T
test_y = test_y.T

In [565]:
pf = np.array(pf)

In [566]:
#  Generating all the hyperparameters in building the neural network (2 inputs, 1 hidden layer and 2 outputs)

In [567]:
# Initializing parameters using random values between-1 and 1 where wt= weight, bs = bias, f = dot product, R=sigmoid

In [595]:
def init_params():
    np.random.seed(4)
    wt1 = np.random.randn(2, 4)
    bs1 = np.random.randn(2)
    wt2 = np.random.randn(4, 2)
    bs2 = np.random.randn(2,)
    return wt1, bs1, wt2, bs2
lamda = 0.5
learning rate = 0.5
iterations = 10

In [601]:
params = init_params()

In [606]:
wt1= params[0]
bs1 = params[1]
wt2= params[2]
bs2= params[3]

params[0], params[1], params[2], params[3]

(array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851],
        [-0.41830152, -1.58457724, -0.64770677,  0.59857517]]),
 array([[ 0.33225003],
        [-1.14747663]]),
 array([[ 0.61866969, -0.08798693],
        [ 0.4250724 ,  0.33225315],
        [-1.15681626,  0.35099715],
        [-0.60688728,  1.54697933]]),
 array([[0.72334161],
        [0.04613557]]))

In [573]:
#defining the sigmoid function and getting the derivative of it

In [614]:
def sigmoid(f1):
        return 1/(1+np.exp(-f1))
    
def der_sigmoid(f1):
    return sigmd(f1)*(1- sigmoid(f1))

In [578]:
#performing the forward propagation

In [623]:
def forward_propagation(wt1, bs1, wt2, bs2, train_x):
    for i in range(0, len(train_x)):
        f1 = wt1.dot(train_x)+ bs1
        R1 = sigmoid(f1) 
        f2=  wt2.dot(f1) + bs2
        R2=  sigmoid(f2)
    return f1, R1, f2, R2

In [571]:
#calculating the loss function

In [598]:
def Loss_function(predict_output, train_y):
    return sqrt(((predict_output, train_y[])** 2).mean())

#where 
predict_output =[]
for i in range (0, len(f2)):
    predict_output_i = 1/1 + np.exp(-0.5 *[f2])


In [580]:
#performing the backward propagation

In [ ]:
def backward_propagation(f1, R1, f2, R2, train_x, train_y):
    m = train_y.size
    der_f2 = R2 - (m * max() + 1)
    der_wt2 = 1 / m * der_f2.dot(R1.T)
    der_bs2 = 1 / np.sum(der_f2, 2)
    der_f1 = wt2.T.dot(der_f2) * der_sigmoid(f):
    der_wt1 = 1 / m * der_f1.dot(x.T)
    der_bs1 = 1 / np.sum(der_f1, 2)
    return der_wt1, der_bs1, der_wt2, der_bs2

In [584]:
#updating to the newly generated parameters

In [585]:
def update_parameters(wt1, bs1, wt2, bs2, der_wt1, der_bs1, der_wt2, der_bs2, alpha):
    wt1 = wt1 - alpha * der_wt1
    wt2 = wt2 - alpha * der_wt2
    bs1 = bs1 - alpha * der_bs1
    bs2 = bs2 - alpha * der_bs2
    return wt1, wt2, bs1, bs2

In [587]:
def gradient_descent(x, y, alpha, iterations,):
    wt1, bs1, wt2, bs2, = init_params()
    for i in range (iterations):
        (f1, R1, f2, R2,) = forward_propagation(wt1, bs1, wt2, bs2, train_x)
        (der_wt1, der_bs1, der_wt2, der_bs2) = backward_propagation(f1, R1, f2, R2, train_x, train_y)
        (wt1,bs1, wt2,  bs2) = update_parameters(wt1, bs1, wt2, bs2, der_wt1, der_bs1, der_wt2, der_bs2, alpha)
    return wt1, wt2, bs1, bs2

In [582]:
#indicating for predictions and accuracy

In [583]:
def get_predictions(R2):
    return np.argmax(R2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

In [588]:
#inputing the network into the training data set

In [ ]:
def fit ()
 def fit(train_x, train_y):
           train_x = x
            train_y = y
            return (x, y)


In [ ]:
wt1, wt2, bs1, bs2 = gradient_descent(train_x,train_y 0.50, 100)